# Spring
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: portal
  config:
    import: 'aws-parameterstore:'

# Tomcat
server:
  servlet:
    context-path: /portal

aws:
  paramstore:
    enabled: true
    region: ap-northeast-1
    prefix: /config
    profileSeparator: _
    failFast: true