spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/sample}?sslmode=require
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASS:admin}

#ログレベルフォーマット
logging.pattern.level=%5p USER_ID:%X{USER_ID} SESSION_ID:%X{SESSION_ID} TRACE_ID:%X{traceId}
